insert into Address (aID, planet, environment, street) values (761, 'Earth', 'forest', '01999 Coolidge Hill');
insert into Address (aID, planet, environment, street) values (8000, 'Earth', 'grassland', '06 Towne Point');
insert into Address (aID, planet, environment, street) values (1918, 'Moon', 'lunar', '1 West Trail');
insert into Address (aID, planet, environment, street) values (9036, 'Earth', 'tundra', '39551 Monica Terrace');
insert into Address (aID, planet, environment, street) values (7717, 'Saturn', 'gas giant', '0 Raven Hill');
insert into Address (aID, planet, environment, street) values (7565, 'Moon', 'lunar', '1199 Basil Place');
insert into Address (aID, planet, environment, street) values (443, 'Earth', 'tundra', '05914 Schurz Place');
insert into Address (aID, planet, environment, street) values (2589, 'Earth', 'grassland', '6613 Saint Paul Hill');
insert into Address (aID, planet, environment, street) values (849, 'Earth', 'aquatic', '734 Melrose Place');
insert into Address (aID, planet, environment, street) values (4409, 'Earth', 'aquatic', '04 Mockingbird Center');
insert into Address (aID, planet, environment, street) values (7485, 'Earth', 'desert', '95 Little Fleur Street');
insert into Address (aID, planet, environment, street) values (6870, 'Earth', 'grassland', '7327 Towne Pass');
insert into Address (aID, planet, environment, street) values (2814, 'Saturn', 'gas giant', '987 Lien Drive');
insert into Address (aID, planet, environment, street) values (4947, 'Saturn', 'gas giant', '53 Nancy Center');
insert into Address (aID, planet, environment, street) values (7047, 'Saturn', 'gas giant', '02 Johnson Street');
insert into Address (aID, planet, environment, street) values (9618, 'Mercury', 'scortched wasteland', '55 Jana Avenue');
insert into Address (aID, planet, environment, street) values (399, 'Moon', 'lunar', '2439 Cambridge Center');
insert into Address (aID, planet, environment, street) values (3740, 'Earth', 'aquatic', '63 Eliot Road');
insert into Address (aID, planet, environment, street) values (4214, 'Mars', 'martian', '2 Rockefeller Way');
insert into Address (aID, planet, environment, street) values (2371, 'Moon', 'lunar', '72912 Cottonwood Avenue');
insert into Address (aID, planet, environment, street) values (9739, 'Moon', 'lunar', '716 Luster Drive');
insert into Address (aID, planet, environment, street) values (4725, 'Earth', 'desert', '8133 Kensington Lane');
insert into Address (aID, planet, environment, street) values (1236, 'Earth', 'desert', '22 Delladonna Hill');
insert into Address (aID, planet, environment, street) values (391, 'Earth', 'forest', '6466 Forest Lane');
insert into Address (aID, planet, environment, street) values (6201, 'Earth', 'tundra', '93097 Muir Place');
insert into Address (aID, planet, environment, street) values (6498, 'Earth', 'grassland', '1 Sullivan Court');
insert into Address (aID, planet, environment, street) values (4148, 'Earth', 'aquatic', '42 Summer Ridge Street');
insert into Address (aID, planet, environment, street) values (9133, 'Earth', 'desert', '4183 Londonderry Way');
insert into Address (aID, planet, environment, street) values (5793, 'Mercury', 'scortched wasteland', '66 5th Trail');
insert into Address (aID, planet, environment, street) values (7327, 'Mars', 'martian', '46 Blaine Place');
insert into Address (aID, planet, environment, street) values (3741, 'Earth', 'desert', '538 Main Junction');
insert into Address (aID, planet, environment, street) values (6193, 'Earth', 'forest', '97 Karstens Avenue');
insert into Address (aID, planet, environment, street) values (3481, 'Venus', 'scortched wasteland', '6608 Gulseth Drive');
insert into Address (aID, planet, environment, street) values (8933, 'Earth', 'grassland', '531 Miller Circle');
insert into Address (aID, planet, environment, street) values (1711, 'Jupiter', 'gas giant', '914 Bluestem Street');
insert into Address (aID, planet, environment, street) values (7671, 'Moon', 'lunar', '9317 Northridge Trail');
insert into Address (aID, planet, environment, street) values (7490, 'Neptune', 'gas giant', '10 Milwaukee Terrace');
insert into Address (aID, planet, environment, street) values (793, 'Earth', 'forest', '997 Shasta Center');
insert into Address (aID, planet, environment, street) values (4181, 'Earth', 'forest', '003 Mendota Crossing');
insert into Address (aID, planet, environment, street) values (6318, 'Moon', 'lunar', '78 Westend Junction');
insert into Address (aID, planet, environment, street) values (4823, 'Venus', 'scortched wasteland', '855 Luster Avenue');
insert into Address (aID, planet, environment, street) values (6044, 'Moon', 'lunar', '8 Stone Corner Point');
insert into Address (aID, planet, environment, street) values (897, 'Earth', 'grassland', '286 Sycamore Street');
insert into Address (aID, planet, environment, street) values (8728, 'Earth', 'grassland', '53238 Saint Paul Plaza');
insert into Address (aID, planet, environment, street) values (1548, 'Venus', 'scortched wasteland', '7298 John Wall Court');
insert into Address (aID, planet, environment, street) values (9332, 'Earth', 'forest', '876 Michigan Crossing');
insert into Address (aID, planet, environment, street) values (7446, 'Earth', 'forest', '7493 Clarendon Road');
insert into Address (aID, planet, environment, street) values (1691, 'Venus', 'scortched wasteland', '6 Wayridge Road');
insert into Address (aID, planet, environment, street) values (9230, 'Moon', 'lunar', '19949 Forest Run Avenue');
insert into Address (aID, planet, environment, street) values (4470, 'Earth', 'tundra', '0780 Carioca Court');
insert into Address (aID, planet, environment, street) values (2218, 'Venus', 'scortched wasteland', '2097 Meadow Vale Place');
insert into Address (aID, planet, environment, street) values (126, 'Earth', 'forest', '72866 Golden Leaf Point');
insert into Address (aID, planet, environment, street) values (3293, 'Neptune', 'gas giant', '57 Merrick Place');
insert into Address (aID, planet, environment, street) values (2783, 'Moon', 'lunar', '94629 Tomscot Point');
insert into Address (aID, planet, environment, street) values (7616, 'Earth', 'tundra', '38941 Lakeland Center');
insert into Address (aID, planet, environment, street) values (6952, 'Earth', 'tundra', '10 Goodland Trail');
insert into Address (aID, planet, environment, street) values (8925, 'Saturn', 'gas giant', '7541 Monterey Alley');
insert into Address (aID, planet, environment, street) values (1221, 'Saturn', 'gas giant', '34869 Monica Hill');
insert into Address (aID, planet, environment, street) values (5769, 'Earth', 'forest', '489 Atwood Terrace');
insert into Address (aID, planet, environment, street) values (8432, 'Earth', 'tundra', '8 Maywood Alley');
insert into Address (aID, planet, environment, street) values (7931, 'Earth', 'grassland', '388 Forest Dale Hill');
insert into Address (aID, planet, environment, street) values (7051, 'Neptune', 'gas giant', '1 Kropf Point');
insert into Address (aID, planet, environment, street) values (2577, 'Saturn', 'gas giant', '9674 Maple Wood Street');
insert into Address (aID, planet, environment, street) values (1083, 'Earth', 'aquatic', '154 Armistice Point');
insert into Address (aID, planet, environment, street) values (6262, 'Moon', 'lunar', '753 Golf Court');
insert into Address (aID, planet, environment, street) values (5091, 'Earth', 'aquatic', '17 Stone Corner Lane');
insert into Address (aID, planet, environment, street) values (7343, 'Moon', 'lunar', '3 Forest Street');
insert into Address (aID, planet, environment, street) values (4076, 'Earth', 'desert', '53148 Brown Lane');
insert into Address (aID, planet, environment, street) values (1799, 'Earth', 'desert', '77382 Bashford Road');
insert into Address (aID, planet, environment, street) values (2006, 'Earth', 'forest', '03 Rockefeller Terrace');
insert into Address (aID, planet, environment, street) values (8155, 'Earth', 'aquatic', '35172 Summit Avenue');
insert into Address (aID, planet, environment, street) values (960, 'Earth', 'forest', '71063 Ruskin Drive');
insert into Address (aID, planet, environment, street) values (6754, 'Earth', 'forest', '90719 Colorado Junction');
insert into Address (aID, planet, environment, street) values (3519, 'Moon', 'lunar', '3180 Pleasure Lane');
insert into Address (aID, planet, environment, street) values (7802, 'Saturn', 'gas giant', '75167 Elgar Pass');
insert into Address (aID, planet, environment, street) values (1312, 'Earth', 'aquatic', '0178 Claremont Court');
insert into Address (aID, planet, environment, street) values (1967, 'Neptune', 'gas giant', '09 Stang Lane');
insert into Address (aID, planet, environment, street) values (8929, 'Earth', 'grassland', '7580 Caliangt Alley');
insert into Address (aID, planet, environment, street) values (7065, 'Moon', 'lunar', '3790 Menomonie Trail');
insert into Address (aID, planet, environment, street) values (5005, 'Earth', 'desert', '67 Tennessee Court');
insert into Address (aID, planet, environment, street) values (6336, 'Moon', 'lunar', '76 Upham Alley');
insert into Address (aID, planet, environment, street) values (7511, 'Moon', 'lunar', '0590 Eggendart Terrace');
insert into Address (aID, planet, environment, street) values (2911, 'Earth', 'desert', '43 Sunfield Point');
insert into Address (aID, planet, environment, street) values (4914, 'Earth', 'aquatic', '8895 Fair Oaks Alley');
insert into Address (aID, planet, environment, street) values (9762, 'Earth', 'grassland', '7 Monica Park');
insert into Address (aID, planet, environment, street) values (9886, 'Moon', 'lunar', '60 Leroy Avenue');
insert into Address (aID, planet, environment, street) values (1170, 'Moon', 'lunar', '00028 Fairfield Trail');
insert into Address (aID, planet, environment, street) values (6904, 'Moon', 'lunar', '36921 Veith Parkway');
insert into Address (aID, planet, environment, street) values (1084, 'Earth', 'grassland', '72 Lawn Center');
insert into Address (aID, planet, environment, street) values (9924, 'Earth', 'aquatic', '12 Rigney Parkway');
insert into Address (aID, planet, environment, street) values (1036, 'Earth', 'tundra', '2 John Wall Court');
insert into Address (aID, planet, environment, street) values (7695, 'Mercury', 'scortched wasteland', '88 North Park');
insert into Address (aID, planet, environment, street) values (2402, 'Earth', 'desert', '3426 Florence Park');
insert into Address (aID, planet, environment, street) values (7866, 'Earth', 'aquatic', '1 Everett Pass');
insert into Address (aID, planet, environment, street) values (3876, 'Earth', 'grassland', '050 Leroy Street');
insert into Address (aID, planet, environment, street) values (9661, 'Venus', 'scortched wasteland', '0587 Laurel Circle');
insert into Address (aID, planet, environment, street) values (5166, 'Earth', 'grassland', '139 Oak Point');
insert into Address (aID, planet, environment, street) values (9294, 'Saturn', 'gas giant', '40 2nd Hill');
insert into Address (aID, planet, environment, street) values (9876, 'Saturn', 'gas giant', '648 Sugar Street');
insert into Address (aID, planet, environment, street) values (1107, 'Moon', 'lunar', '0 Esch Circle');
insert into Address (aID, planet, environment, street) values (9691, 'Saturn', 'gas giant', '3 Ruskin Avenue');
insert into Address (aID, planet, environment, street) values (7329, 'Earth', 'aquatic', '5 Novick Place');
insert into Address (aID, planet, environment, street) values (6561, 'Earth', 'grassland', '8401 Delladonna Drive');
insert into Address (aID, planet, environment, street) values (7126, 'Earth', 'tundra', '11 Crescent Oaks Pass');
insert into Address (aID, planet, environment, street) values (6840, 'Earth', 'grassland', '999 Everett Park');
insert into Address (aID, planet, environment, street) values (4264, 'Venus', 'scortched wasteland', '5786 Huxley Alley');
insert into Address (aID, planet, environment, street) values (491, 'Earth', 'tundra', '68 Graceland Lane');
insert into Address (aID, planet, environment, street) values (6769, 'Earth', 'aquatic', '49 Buena Vista Place');
insert into Address (aID, planet, environment, street) values (1077, 'Venus', 'scortched wasteland', '61696 Mayer Hill');
insert into Address (aID, planet, environment, street) values (6549, 'Neptune', 'gas giant', '222 Welch Place');
insert into Address (aID, planet, environment, street) values (5651, 'Earth', 'grassland', '52109 Veith Plaza');
insert into Address (aID, planet, environment, street) values (8905, 'Earth', 'forest', '6 Warrior Point');
insert into Address (aID, planet, environment, street) values (5915, 'Mercury', 'scortched wasteland', '05804 Riverside Road');
insert into Address (aID, planet, environment, street) values (4773, 'Moon', 'lunar', '287 Sullivan Junction');
insert into Address (aID, planet, environment, street) values (4078, 'Earth', 'forest', '0184 Vidon Park');
insert into Address (aID, planet, environment, street) values (7915, 'Earth', 'forest', '8 Hagan Parkway');
insert into Address (aID, planet, environment, street) values (576, 'Moon', 'lunar', '9 Spohn Crossing');
insert into Address (aID, planet, environment, street) values (7917, 'Earth', 'forest', '18 Ramsey Place');
insert into Address (aID, planet, environment, street) values (6452, 'Earth', 'desert', '06699 Elmside Junction');
insert into Address (aID, planet, environment, street) values (6581, 'Mercury', 'scortched wasteland', '10 Pankratz Park');
insert into Address (aID, planet, environment, street) values (1771, 'Moon', 'lunar', '7 Holmberg Road');
insert into Address (aID, planet, environment, street) values (8826, 'Moon', 'lunar', '31 Warbler Avenue');
insert into Address (aID, planet, environment, street) values (289, 'Moon', 'lunar', '6646 Lerdahl Way');
insert into Address (aID, planet, environment, street) values (6324, 'Earth', 'forest', '459 Schlimgen Drive');
insert into Address (aID, planet, environment, street) values (3996, 'Moon', 'lunar', '6303 Blaine Avenue');
insert into Address (aID, planet, environment, street) values (962, 'Earth', 'aquatic', '6495 Moland Road');
insert into Address (aID, planet, environment, street) values (5947, 'Earth', 'forest', '8814 Union Place');
insert into Address (aID, planet, environment, street) values (1696, 'Earth', 'tundra', '45 Kipling Avenue');
insert into Address (aID, planet, environment, street) values (4310, 'Mars', 'martian', '653 Hanson Crossing');
insert into Address (aID, planet, environment, street) values (3389, 'Saturn', 'gas giant', '4 Melrose Pass');
insert into Address (aID, planet, environment, street) values (1128, 'Earth', 'forest', '1 Orin Road');
insert into Address (aID, planet, environment, street) values (3215, 'Saturn', 'gas giant', '222 Bluejay Crossing');
insert into Address (aID, planet, environment, street) values (2452, 'Earth', 'forest', '6 Colorado Hill');
insert into Address (aID, planet, environment, street) values (6109, 'Moon', 'lunar', '200 Spohn Hill');
insert into Address (aID, planet, environment, street) values (2209, 'Earth', 'desert', '6330 Bobwhite Junction');
insert into Address (aID, planet, environment, street) values (2406, 'Venus', 'scortched wasteland', '6486 Dakota Road');
insert into Address (aID, planet, environment, street) values (3005, 'Moon', 'lunar', '84678 Union Plaza');
insert into Address (aID, planet, environment, street) values (8436, 'Jupiter', 'gas giant', '52078 Miller Drive');
insert into Address (aID, planet, environment, street) values (5076, 'Moon', 'lunar', '7 Corben Drive');
insert into Address (aID, planet, environment, street) values (5443, 'Earth', 'aquatic', '712 Sauthoff Junction');
insert into Address (aID, planet, environment, street) values (6489, 'Mars', 'martian', '3 Paget Court');
insert into Address (aID, planet, environment, street) values (6252, 'Moon', 'lunar', '47 Oneill Trail');
insert into Address (aID, planet, environment, street) values (8694, 'Moon', 'lunar', '26 Corry Street');
insert into Address (aID, planet, environment, street) values (2681, 'Mars', 'martian', '99 Brickson Park Center');
insert into Address (aID, planet, environment, street) values (5972, 'Earth', 'aquatic', '2188 Westerfield Court');
insert into Address (aID, planet, environment, street) values (7981, 'Moon', 'lunar', '7942 Northwestern Park');
insert into Address (aID, planet, environment, street) values (4889, 'Earth', 'grassland', '607 Valley Edge Center');
insert into Address (aID, planet, environment, street) values (5501, 'Mars', 'martian', '0695 Fordem Avenue');
insert into Address (aID, planet, environment, street) values (6566, 'Moon', 'lunar', '59 Debra Terrace');
insert into Address (aID, planet, environment, street) values (9596, 'Earth', 'tundra', '8 Stuart Lane');
insert into Address (aID, planet, environment, street) values (1499, 'Earth', 'forest', '0375 Glendale Trail');
insert into Address (aID, planet, environment, street) values (8857, 'Earth', 'grassland', '16502 Linden Parkway');
insert into Address (aID, planet, environment, street) values (6640, 'Moon', 'lunar', '4 Golf View Alley');
insert into Address (aID, planet, environment, street) values (5881, 'Moon', 'lunar', '0416 Arrowood Court');
insert into Address (aID, planet, environment, street) values (6830, 'Earth', 'desert', '85 Orin Place');
insert into Address (aID, planet, environment, street) values (4873, 'Moon', 'lunar', '41 Thierer Park');
insert into Address (aID, planet, environment, street) values (3083, 'Earth', 'desert', '1526 Fallview Junction');
insert into Address (aID, planet, environment, street) values (6326, 'Earth', 'forest', '6 Forest Crossing');
insert into Address (aID, planet, environment, street) values (7000, 'Mercury', 'scortched wasteland', '32499 Waxwing Terrace');
insert into Address (aID, planet, environment, street) values (1865, 'Neptune', 'gas giant', '49677 Crest Line Parkway');
insert into Address (aID, planet, environment, street) values (9632, 'Earth', 'aquatic', '6 Blue Bill Park Lane');
insert into Address (aID, planet, environment, street) values (2051, 'Mars', 'martian', '9 Welch Crossing');
insert into Address (aID, planet, environment, street) values (690, 'Earth', 'aquatic', '02167 Lighthouse Bay Avenue');
insert into Address (aID, planet, environment, street) values (9758, 'Moon', 'lunar', '26790 Lukken Center');
insert into Address (aID, planet, environment, street) values (9915, 'Saturn', 'gas giant', '500 Michigan Terrace');
insert into Address (aID, planet, environment, street) values (1813, 'Moon', 'lunar', '0 Hooker Hill');
insert into Address (aID, planet, environment, street) values (1045, 'Moon', 'lunar', '0005 Esker Trail');
insert into Address (aID, planet, environment, street) values (145, 'Earth', 'aquatic', '7147 6th Court');
insert into Address (aID, planet, environment, street) values (7957, 'Earth', 'tundra', '0697 Packers Drive');
insert into Address (aID, planet, environment, street) values (4390, 'Jupiter', 'gas giant', '581 School Street');
insert into Address (aID, planet, environment, street) values (1141, 'Mars', 'martian', '8 Raven Pass');
insert into Address (aID, planet, environment, street) values (3799, 'Earth', 'grassland', '9 Bowman Avenue');
insert into Address (aID, planet, environment, street) values (6852, 'Earth', 'desert', '12546 Loeprich Pass');
insert into Address (aID, planet, environment, street) values (4495, 'Saturn', 'gas giant', '717 Moose Avenue');
insert into Address (aID, planet, environment, street) values (2205, 'Mars', 'martian', '794 Melvin Lane');
insert into Address (aID, planet, environment, street) values (5660, 'Moon', 'lunar', '270 Marcy Center');
insert into Address (aID, planet, environment, street) values (7922, 'Earth', 'aquatic', '66440 Kipling Parkway');
insert into Address (aID, planet, environment, street) values (329, 'Earth', 'tundra', '08376 Delaware Alley');
insert into Address (aID, planet, environment, street) values (8320, 'Earth', 'desert', '89 Arkansas Hill');
insert into Address (aID, planet, environment, street) values (591, 'Mars', 'martian', '09626 Hansons Court');
insert into Address (aID, planet, environment, street) values (6077, 'Earth', 'tundra', '82 Calypso Parkway');
insert into Address (aID, planet, environment, street) values (2141, 'Neptune', 'gas giant', '7 Lukken Center');
insert into Address (aID, planet, environment, street) values (8186, 'Earth', 'grassland', '62 Vera Court');
insert into Address (aID, planet, environment, street) values (6875, 'Earth', 'tundra', '38 Donald Lane');
insert into Address (aID, planet, environment, street) values (2872, 'Moon', 'lunar', '27 Stoughton Place');
insert into Address (aID, planet, environment, street) values (6006, 'Earth', 'tundra', '279 Superior Junction');
insert into Address (aID, planet, environment, street) values (4401, 'Earth', 'desert', '84 Northport Park');
insert into Address (aID, planet, environment, street) values (3356, 'Moon', 'lunar', '283 Lakeland Point');
insert into Address (aID, planet, environment, street) values (397, 'Mars', 'martian', '52637 Pennsylvania Road');
insert into Address (aID, planet, environment, street) values (286, 'Neptune', 'gas giant', '81 Delaware Drive');
insert into Address (aID, planet, environment, street) values (6979, 'Mercury', 'scortched wasteland', '27747 Helena Terrace');
insert into Address (aID, planet, environment, street) values (7517, 'Moon', 'lunar', '8 Donald Center');
insert into Address (aID, planet, environment, street) values (2839, 'Moon', 'lunar', '81586 Starling Alley');
insert into Address (aID, planet, environment, street) values (8198, 'Earth', 'aquatic', '60972 Loeprich Trail');
insert into Address (aID, planet, environment, street) values (3851, 'Earth', 'desert', '0 Shelley Place');
insert into Address (aID, planet, environment, street) values (9595, 'Earth', 'aquatic', '5 Goodland Drive');
insert into Address (aID, planet, environment, street) values (4591, 'Moon', 'lunar', '51504 Bowman Drive');
insert into Address (aID, planet, environment, street) values (7312, 'Earth', 'tundra', '0579 Main Park');
insert into Address (aID, planet, environment, street) values (701, 'Venus', 'scortched wasteland', '4 Dakota Alley');
insert into Address (aID, planet, environment, street) values (4842, 'Moon', 'lunar', '4975 Independence Circle');
insert into Address (aID, planet, environment, street) values (6185, 'Venus', 'scortched wasteland', '25 Mayer Pass');
insert into Address (aID, planet, environment, street) values (9649, 'Earth', 'desert', '8 Lawn Road');
insert into Address (aID, planet, environment, street) values (6824, 'Saturn', 'gas giant', '443 Ramsey Junction');
insert into Address (aID, planet, environment, street) values (903, 'Earth', 'grassland', '4751 Waywood Junction');
insert into Address (aID, planet, environment, street) values (7921, 'Moon', 'lunar', '58240 Mosinee Pass');
insert into Address (aID, planet, environment, street) values (6550, 'Saturn', 'gas giant', '8 Mariners Cove Place');
insert into Address (aID, planet, environment, street) values (1587, 'Earth', 'forest', '794 Corscot Hill');
insert into Address (aID, planet, environment, street) values (7219, 'Moon', 'lunar', '2085 Jay Hill');
insert into Address (aID, planet, environment, street) values (2761, 'Earth', 'forest', '9 Lunder Parkway');
insert into Address (aID, planet, environment, street) values (1901, 'Earth', 'aquatic', '61 Quincy Avenue');
insert into Address (aID, planet, environment, street) values (6164, 'Earth', 'forest', '61 Golf Lane');
insert into Address (aID, planet, environment, street) values (7606, 'Earth', 'forest', '6162 East Way');
