insert into Upgrade (upgID, upgrade_name, price) values (1, 'Professional Sound System', 4000);
insert into Upgrade (upgID, upgrade_name, price) values (2, 'Voice Activated Engine Start', 1000);
insert into Upgrade (upgID, upgrade_name, price) values (3, 'Chrome Plated Exhaust', 300);
insert into Upgrade (upgID, upgrade_name, price) values (4, 'Gold Hood Ornament', 500);
insert into Upgrade (upgID, upgrade_name, price) values (5, 'Sunroof', 1000);
insert into Upgrade (upgID, upgrade_name, price) values (6, 'Leather Seats', 3000);
insert into Upgrade (upgID, upgrade_name, price) values (7, 'Leather Interior', 2000);
insert into Upgrade (upgID, upgrade_name, price) values (8, 'Autonomous Driving', 12000);
insert into Upgrade (upgID, upgrade_name, price) values (9, 'Carbon Fiber Rims', 3000);
insert into Upgrade (upgID, upgrade_name, price) values (10, 'Turbo Engine', 115000);
insert into Upgrade (upgID, upgrade_name, price) values (11, 'Bulletproof Tires', 2000);
insert into Upgrade (upgID, upgrade_name, price) values (12, 'Bulletproof Windows', 30000);
insert into Upgrade (upgID, upgrade_name, price) values (13, 'Bulletproof Body', 25000);
insert into Upgrade (upgID, upgrade_name, price) values (14, 'Heavy Duty Chassis', 10000);
insert into Upgrade (upgID, upgrade_name, price) values (15, 'HEPA Air Filtration System', 6000);
insert into Upgrade (upgID, upgrade_name, price) values (16, 'Touch Screen Displays', 500);
insert into Upgrade (upgID, upgrade_name, price) values (17, 'Tow Hitch', 1000);
insert into Upgrade (upgID, upgrade_name, price) values (18, 'Race Brakes', 24000);
insert into Upgrade (upgID, upgrade_name, price) values (19, 'Carbon Fiber Spoiler', 1900);
insert into Upgrade (upgID, upgrade_name, price) values (20, 'Carbon Fiber Skirts', 800);
insert into Upgrade (upgID, upgrade_name, price) values (21, 'Race Transmission', 40000);
insert into Upgrade (upgID, upgrade_name, price) values (22, 'Bespoke Suspension Tuning', 8000);
